vim.cmd.set("clipboard=unnamedplus")
vim.cmd.set("relativenumber")
vim.cmd.colorscheme("lightside")
vim.cmd.set("signcolumn=yes")
vim.cmd.set("cursorline")
vim.cmd.set("number")
vim.cmd.set("expandtab")
vim.cmd.set("tabstop=4")
vim.cmd.set("shiftwidth=4")
vim.cmd.set("notermguicolors")
vim.o.laststatus = 3
vim.cmd.set("wfh")
